### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by WencongY** [thunlp/OpenAttack#123]
Hello,

I've noticed that a few scripts, such as workflow.py, give overflow errors. I'm using Python 3.8 in anaconda environment with all required libraries installed, Can you please share your thoughts on this? Thank you!

Traceback (most recent call last):
  File "examples/workflow.py", line 24, in <module>
    main()
  File "examples/workflow.py", line 7, in main
    clsf = OpenAttack.DataManager.load("Victim.BiLSTM.SST")
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/site-packages/OpenAttack-1.1.1-py3.8.egg/OpenAttack/data_manager.py", line 72, in load
    cls.data_reference[data_name] = cls.data_loader[data_name](
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/site-packages/OpenAttack-1.1.1-py3.8.egg/OpenAttack/data/victim_bilstm.py", line 50, in LOAD
    word_vector = OpenAttack.DataManager.load("AttackAssist.GloVe")
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/site-packages/OpenAttack-1.1.1-py3.8.egg/OpenAttack/data_manager.py", line 64, in load
    cls.download(data_name)
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/site-packages/OpenAttack-1.1.1-py3.8.egg/OpenAttack/data_manager.py", line 175, in download
    cls.data_download[data_name](path)
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/site-packages/OpenAttack-1.1.1-py3.8.egg/OpenAttack/utils/zip_downloader.py", line 16, in DOWNLOAD
    zf = zipfile.ZipFile(io.BytesIO(f.read()))
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/http/client.py", line 471, in read
    s = self._safe_read(self.length)
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/user/opt/anaconda3/envs/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
OverflowError: signed integer is greater than maximum

**Comment by a710128** [comment]
Thank you for your feedback. We also noticed this earlier and solved this problem ( See 44de541fb3cce46430dc0de4ddbc66c534edec49 , it's on the dev branch now ). I guess this may be due to Python 3.8 changed the implementation of urllib.request.

**Comment by Fanchao-Qi** [comment]
This problem has been solved in the newest version. If you still encounter the problem, please feel free to reopen it.
