### ISSUE TITLE
decode problem

### ISSUE THREAD

**Issue by hmtbgc** [thunlp/OpenAttack#124]
Hi. When I tried the first example in "Usage Examples" on my Linux PC, I met a decode problem:

 _Traceback (most recent call last):
  File "/root/root/Desktop/textAttackTest/test.py", line 7, in <module>
    attacker = oa.attackers.GeneticAttacker()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/OpenAttack/attackers/genetic.py", line 71, in __init__
    self.config["substitute"] = CounterFittedSubstitute()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/OpenAttack/substitutes/counter_fit.py", line 16, in __init__
    self.wordvec = DataManager.load("AttackAssist.CounterFit")
  File "/usr/local/miniconda3/lib/python3.6/site-packages/OpenAttack/data_manager.py", line 73, in load
    cls.data_path[data_name]
  File "/usr/local/miniconda3/lib/python3.6/site-packages/OpenAttack/data/counter_fit.py", line 22, in LOAD
    for line in f.readlines():
  File "/usr/local/miniconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]_
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1640: ordinal not in range(128)**
It seemed nothing got wrong. 
Any idea? Thanks.

**Comment by Cypredar** [comment]
Maybe you should try to solve the problem by changing the encoding type; we will  revisit and resolve the issue as soon as possible.

**Comment by Fanchao-Qi** [comment]
This problem has been solved in the newest version. If you still encounter the problem, please feel free to reopen it.
