### ISSUE TITLE
Tried to install but error message: "Invalid version: 'test'"

### ISSUE THREAD

**Issue by somechan** [thunlp/OpenAttack#276]
Hi! thanks for your great package, but when I tired to install it returned an error. Did you guys change the version or so?

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_normalization.py", line 59, in safe_version
    return str(packaging.version.Version(v))
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/OpenAttack/setup.py", line 15, in <module>
    setuptools.setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 491, in __init__
    self.patch_missing_pkg_info(attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 480, in patch_missing_pkg_info
    dist._version = _normalization.safe_version(str(attrs['version']))
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_normalization.py", line 62, in safe_version
    return str(packaging.version.Version(attempt))
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'test'

**Comment by xingyizhao** [comment]
The same:
![image](https://github.com/thunlp/OpenAttack/assets/90595479/4aa2705e-e4bd-46fe-af52-40287d0a90a7)

**Comment by xingyizhao** [comment]
I think the reason is you need to set your python==3.6. After I did that, everything worked.
![image](https://github.com/thunlp/OpenAttack/assets/90595479/bfedc0a7-6006-4816-9f31-c71db6878105)

Your python environment should be 3.6.

**Comment by xingyizhao** [comment]
![image](https://github.com/thunlp/OpenAttack/assets/90595479/1e79b1fe-269f-402e-b571-7d8df6edd862)
