### ISSUE TITLE
AttributeError: 'FileFinder' object has no attribute 'find_loader'

### ISSUE THREAD

**Issue by Q1ngS0ng** [thunlp/OpenAttack#279]
Traceback (most recent call last):
  File "/root/RAG-YuWan/OpenAttack/demo.py", line 1, in <module>
    import OpenAttack
  File "/root/RAG-YuWan/OpenAttack/OpenAttack/__init__.py", line 2, in <module>
    from .data_manager import DataManager
  File "/root/RAG-YuWan/OpenAttack/OpenAttack/data_manager.py", line 4, in <module>
    from .data import data_list
  File "/root/RAG-YuWan/OpenAttack/OpenAttack/data/__init__.py", line 61, in <module>
    data_list = load_data()
                ^^^^^^^^^^^
  File "/root/RAG-YuWan/OpenAttack/OpenAttack/data/__init__.py", line 38, in load_data
    data = data.module_finder.find_loader(data.name)[0].load_module()

**Comment by GrigLog** [comment]
It seems that find_loader method of importlib.machinery.FileFinder has been removed in Python 3.12, and the library is not updated for this version yet
